import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
globalThis.HTMLElement = class {};
const registered = new Map();
globalThis.customElements = { get: name => registered.get(name), define: (name, element) => registered.set(name, element) };
globalThis.window = {};
const source = await readFile(new URL('../slate-heating-card.js', import.meta.url), 'utf8');
const { WEEK, weeklyDays, scheduleKey, validateProgramme, wiserAction, saveProgramme, boostConfirmed, oilReading } = await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
const heating = {Id:1,Name:'Kitchen',Type:'Heating',ScheduleData:[{day:'All',slots:[{Time:'06:00',Setpoint:19},{Time:'22:00',Setpoint:16}]}]};
const water = {Id:1000,Name:'Hot Water',Type:'OnOff',ScheduleData:WEEK.map(day=>({day,slots:day==='Saturday'?[{Time:'06:00',Setpoint:'Off'}]:[]}))};
const expanded = weeklyDays(heating);
assert.equal(expanded.length,7);
expanded[0].slots[0].Setpoint=20;
assert.equal(expanded[1].slots[0].Setpoint,19);
assert.equal(scheduleKey(heating),scheduleKey({...heating,ScheduleData:weeklyDays(heating)}));
assert.equal(validateProgramme(water,'OnOff').ScheduleData[0].slots.length,0,'Preserve days with no changes.');
const edit = slots => ({...heating,ScheduleData:[{day:'All',slots}]});
assert.throws(()=>validateProgramme(edit([{Time:'25:00',Setpoint:19}]),'Heating'),/valid time/);
assert.throws(()=>validateProgramme(edit([{Time:'06:00',Setpoint:19},{Time:'06:00',Setpoint:20}]),'Heating'),/same time/);
assert.throws(()=>validateProgramme(edit([{Time:'06:00',Setpoint:19.2}]),'Heating'),/0.5/);
assert.throws(()=>validateProgramme(edit([{Time:'06:00',Setpoint:NaN}]),'Heating'),/temperature/);
assert.throws(()=>validateProgramme(edit([]),'Heating'),/at least one/);
assert.throws(()=>validateProgramme(edit(Array.from({length:9},(_,i)=>({Time:`${String(i).padStart(2,'0')}:00`,Setpoint:19}))),'Heating'),/eight/);
assert.throws(()=>validateProgramme(edit([{Time:'06:00',Setpoint:19}]),'OnOff'),/On or Off/);
assert.equal(validateProgramme(edit([{Time:'06:00',Setpoint:'Off'}]),'Heating').ScheduleData[0].slots[0].Setpoint,'Off');
let stored=structuredClone(heating),calls=[],state={entity_id:'climate.heating',state:'auto',attributes:{schedule_id:1,temperature:19}};
const target={entityId:state.entity_id,hub:'Test hub',type:'Heating',id:1,min:5,max:30};
const fake={
 callService:async(...args)=>calls.push(args),
 callWS:async request=>{calls.push(request);if(request.type==='get_states')return [state];if(request.type==='wiser/schedule/save'){stored=structuredClone(request.schedule);return 'success';}return structuredClone(stored);}
};
const changed=edit([{Time:'07:00',Setpoint:20},{Time:'22:00',Setpoint:16}]);
const result=await saveProgramme(fake,target,changed,scheduleKey(heating));
assert.equal(result.ScheduleData[0].slots[0].Setpoint,20);
assert.equal(calls.find(call=>call.type==='wiser/schedule/save').schedule_id,1);
calls=[];
await assert.rejects(()=>saveProgramme(fake,target,changed,scheduleKey(heating)),/changed elsewhere/);
assert.ok(!calls.some(call=>call.type==='wiser/schedule/save'));
state.attributes.schedule_id=2;
await assert.rejects(()=>saveProgramme(fake,target,changed,scheduleKey(changed)),/assigned programme changed/);
state.attributes.schedule_id=1;stored=heating;
const rejected={...fake,callWS:async request=>request.type==='wiser/schedule/save'?'success':fake.callWS(request)};
await assert.rejects(()=>saveProgramme(rejected,target,changed,scheduleKey(heating)),/did not confirm/);
await wiserAction(fake,state.entity_id,'set_temperature',{temperature:19},s=>s.attributes.temperature===19);
await assert.rejects(()=>wiserAction(fake,state.entity_id,'set_temperature',{temperature:20},s=>s.attributes.temperature===20),/not confirmed/);
// The Wiser climate entity exposes remaining minutes, although its underlying API uses seconds.
for(const minutes of [30,60,120]) assert.equal(boostConfirmed({attributes:{is_boosted:true,boost_time_remaining:minutes-1}},minutes),true);
assert.equal(boostConfirmed({attributes:{is_boosted:true,boost_time_remaining:120}},30),false,'A previous longer boost must not count as a confirmed 30-minute boost.');
assert.equal(boostConfirmed({attributes:{is_boosted:false,boost_time_remaining:30}},30),false);
// Tank probes must update the card even when neither climate entity changes.
const card = Object.create(registered.get('wiser-slate-card').prototype);
let renders = 0;
card.render = () => renders++;
card.setConfig({heating_entity:'climate.heating',hot_water_entity:'climate.hot_water',tank_top_entity:'sensor.tank_top',tank_middle_entity:'sensor.tank_middle',tank_bottom_entity:'sensor.tank_bottom',oil_level_entity:'sensor.oil_level',oil_percentage_entity:'sensor.oil_percentage'});
const middle = card.config.tank_middle_entity, bottom = card.config.tank_bottom_entity;
const sensorStates = { [middle]: {state:'28.3125',attributes:{}}, [bottom]: {state:'36.875',attributes:{}} };
card.hass = {states:sensorStates,locale:{language:'en'}};
const initialRenders = renders;
card.hass = {states:{...sensorStates,[middle]:{state:'28.375',attributes:{}}},locale:{language:'en'}};
assert.equal(renders,initialRenders+1);
card.hass = {states:{...card._hass.states,[bottom]:{state:'unavailable',attributes:{}}},locale:{language:'en'}};
assert.equal(renders,initialRenders+2);
card.hass = {...card._hass};
assert.equal(renders,initialRenders+2);
assert.equal(card.temperature('36.875'),'36.9');
assert.equal(card.temperature('0'),'0');
assert.equal(card.temperature('unknown'),'—');
console.log('Wiser checks passed: weekly expansion, empty days, time/temperature/limit validation, native API payloads, external edits, assignment changes and actual-state confirmation.');
console.log('Tank sensor checks passed: independent updates, unavailable states and temperature rounding.');
// Oil changes must refresh independently; empty or invalid data must never look like an empty tank.
const oilLevel = card.config.oil_level_entity, oilPercent = card.config.oil_percentage_entity;
const beforeOil = renders;
card.hass = { ...card._hass, states: { ...card._hass.states, [oilLevel]: { state: '511', attributes: {} } } };
card.hass = { ...card._hass, states: { ...card._hass.states, [oilPercent]: { state: '56.8', attributes: {} } } };
assert.equal(renders, beforeOil + 2);
assert.equal(oilReading({state:'511'}), 511);
assert.equal(oilReading({state:'56.8'}, 100), 56.8);
assert.equal(oilReading({state:'0'}, 100), 0);
for (const value of [null, '', ' ', 'unknown', 'unavailable', '-1', 'NaN', '101']) assert.equal(oilReading({state:value}, 100), null);
assert.equal(oilReading(undefined), null);
console.log('Oil sensor checks passed: independent updates, valid empty tank, invalid and unavailable readings.');
const { tankTemperature, tankColour } = await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
const beforeTop = renders;
card.hass = {...card._hass, states:{...card._hass.states,[card.config.tank_top_entity]:{state:'46.6',attributes:{}}}};
assert.equal(renders, beforeTop + 1);
for (const state of ['', ' ', 'unknown', 'unavailable', null, 'NaN']) assert.equal(tankTemperature({state}), null);
assert.equal(tankTemperature({state:'0'}),0);
assert.equal(tankColour({state:'68',attributes:{unit_of_measurement:'°F'}}),tankColour({state:'20'}));
assert.equal(tankColour({state:'60'}),tankColour({state:'90'}));
assert.notEqual(tankColour({state:'27'}),tankColour({state:'47'}));
assert.match(tankColour({state:'unavailable'}),/disabled/);
console.log('Three tank layers passed: top-sensor refresh, missing readings, fixed colour scale and Fahrenheit conversion.');
const { hotTankPercent } = await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
const probes = values => values.map(state => ({state:String(state),attributes:{unit_of_measurement:'°C'}}));
assert.equal(hotTankPercent(probes([48,48.8,50.8])),100,'Today fully heated');
assert.equal(hotTankPercent(probes([30.1,46.3,48.9])),70,'Today after first draw-off');
assert.equal(hotTankPercent(probes([23.4,27.9,44])),10,'Today after shower: hot top, cool middle');
assert.equal(hotTankPercent(probes([20,40,60])),50);
assert.equal(hotTankPercent(probes([39,39,39])),0,'Lukewarm throughout is not a hot reserve');
assert.equal(hotTankPercent(probes([40,40,40])),100,'Reference is inclusive');
assert.equal(hotTankPercent(probes([60,40,20])),50,'Non-monotonic or reversed profiles do not divide by zero');
assert.equal(hotTankPercent(probes([40,30,40])),0);
for (const values of [[85,45,50],[-127,45,50],['unavailable',45,50],['',45,50]]) assert.equal(hotTankPercent(probes(values)),null);
assert.equal(hotTankPercent([{state:'68',attributes:{unit_of_measurement:'°F'}},{state:'104',attributes:{unit_of_measurement:'°F'}},{state:'140',attributes:{unit_of_measurement:'°F'}}]),50);
assert.equal(hotTankPercent(probes([20,40,60]),50),25);
assert.equal(hotTankPercent(probes([20,40])),0);
assert.equal(hotTankPercent(probes([60,20])),50);
assert.equal(hotTankPercent(probes([60])),null);
assert.equal(hotTankPercent(probes([])),null);
assert.equal(hotTankPercent(probes([50,45,40,35,30])),50);
assert.equal(hotTankPercent(probes([50,45,35,30])),50);
assert.equal(hotTankPercent(probes([50,45,'unavailable',35,30])),null);
assert.equal(hotTankPercent(probes(Array(12).fill(50))),100);
console.log('Hot water estimate passed: real-day examples, threshold interpolation, missing/error readings and Celsius/Fahrenheit.');
const { OIL_FIELDS, oilCosts } = await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
const OIL_ENTITIES=Object.fromEntries(Object.keys(OIL_FIELDS).map(k=>[k,`sensor.test_${k}`]));
const oilConfig=Object.fromEntries(Object.entries(OIL_FIELDS).map(([k,field])=>[field,OIL_ENTITIES[k]]));
const sampleOil = Object.fromEntries(Object.entries({usage:0.8,date:'2026-09-12T05:12:03+00:00',price:1.55,priceKwh:1.55/9,heatingHours:1,waterHours:3,heatingKnown:24,waterKnown:24}).map(([key,state])=>[OIL_ENTITIES[key],{state:String(state),attributes:{unit_of_measurement:key==='price'?'EUR/L':key==='priceKwh'?'EUR/kWh':undefined}}]));

assert.equal(oilCosts(sampleOil,oilConfig).cost,null,'Wait for two real tank readings, never assume a daily report spans the gap');
const savedReport={report:Date.parse('2026-09-12T05:12:03+00:00')/1000,start:Date.parse('2026-09-09T05:12:03+00:00')/1000,litres:0.8,cost:1.12,heating:.28,water:.84};
sampleOil[OIL_ENTITIES.total]={state:'1.12',attributes:{ledger:{last:savedReport}}};
assert.equal(oilCosts(sampleOil,oilConfig).cost,1.12,'Saved reports retain their price');
assert.equal(oilCosts(sampleOil,oilConfig).litres,0.8);
assert.equal(oilCosts(sampleOil,oilConfig).report-oilCosts(sampleOil,oilConfig).start,3*86400000);
savedReport.cost=null;savedReport.heating=null;savedReport.water=null;
assert.equal(oilCosts(sampleOil,oilConfig).cost,null,'Unpriced report cannot look free or be silently repriced');
delete sampleOil[OIL_ENTITIES.total];
assert.equal(oilCosts(sampleOil,oilConfig).heating,null,'No split when activity coverage is incomplete');
sampleOil[OIL_ENTITIES.price].attributes.unit_of_measurement='GBP/L';sampleOil[OIL_ENTITIES.priceKwh].state='unavailable';
assert.equal(oilCosts(sampleOil,oilConfig).price,null);
assert.equal(oilCosts({}).cost,null);
console.log('Oil cost card checks passed: litres/prices, allocation, frozen report costs, missing history and unknown units.');
const {normalizeConfig,DEFAULTS,configForm,oilEntities} = await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
assert.deepEqual(normalizeConfig({heating_entity:'climate.lounge'}).sections,['heating']);
assert.deepEqual(normalizeConfig({tank_top_entity:'sensor.top'}).sections,['water']);
assert.deepEqual(normalizeConfig({oil_level_entity:'sensor.fuel'}).sections,['oil']);
assert.deepEqual(normalizeConfig({}).sections,[]);
assert.deepEqual(normalizeConfig({sections:['oil','water','heating']}).sections,['oil','water','heating']);
assert.equal(normalizeConfig({tank_top_entity:''}).tank_top_entity,undefined);
for (const c of [{sections:['water','water']},{sections:['unknown']},{heating_entity:'switch.boiler'},{tank_top_entity:'climate.room'},{currency:'euros'},{energy_per_litre:0},{show_boost:'false'},{layout:'wide'}]) assert.throws(()=>normalizeConfig(c));
assert.equal(normalizeConfig({heating_entity:'climate.room',grid_options:{columns:12}}).grid_options.columns,12);
assert.deepEqual(oilEntities({oil_cost_entity:'sensor.one'}).total,'sensor.one');
assert.deepEqual(oilEntities({oil_cost_entity:'sensor.two'}).total,'sensor.two');
assert.equal(oilEntities({}).total,undefined,'No household defaults leak into a new card');
const formFields=s=>s.flatMap(f=>f.schema?formFields(f.schema):[f.name]);
for(const field of [...Object.values(OIL_FIELDS),'sections','layout','heating_entities','hot_water_entity','tank_entities','show_tank_estimate']) assert.ok(formFields(configForm().schema).includes(field),`${field} editable in UI`);
assert.equal(typeof registered.get('slate-heating-card').getConfigForm,'function');
assert.equal(window.customCards.filter(c=>c.type==='slate-heating-card').length,1);
assert.ok(!Object.keys(normalizeConfig({})).some(key=>key.endsWith('_entity')), 'Release defaults must not include household entity mappings');
console.log('Composable checks passed: optional sections, ordering, independent instances, validation, native editor schema, legacy type and no household defaults.');

assert.deepEqual(normalizeConfig({tank_entities:['sensor.a','sensor.b','sensor.c','sensor.d']}).tank_entities,['sensor.a','sensor.b','sensor.c','sensor.d']);
assert.deepEqual(normalizeConfig({tank_top_entity:'sensor.top',tank_bottom_entity:'sensor.bottom'}).tank_entities,['sensor.top','sensor.bottom']);
assert.deepEqual(normalizeConfig({tank_top_entity:'sensor.top',tank_entities:[]}).tank_entities,[]);
assert.throws(()=>normalizeConfig({tank_entities:['sensor.a','sensor.a']}));
assert.throws(()=>normalizeConfig({tank_entities:['climate.a']}));
console.log('N-probe checks passed: zero, one, two, three, four, five and twelve probes, mixed units, missing data, ordering and legacy migration.');
const {heatingCapabilities,modeCommand,entityAction}=await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
assert.deepEqual(normalizeConfig({heating_entities:['climate.a','climate.b']}).sections,['heating']);
assert.deepEqual(normalizeConfig({heating_entity:'climate.old'}).heating_entities,['climate.old']);
assert.throws(()=>normalizeConfig({heating_entities:['climate.a','climate.a']}));
assert.throws(()=>normalizeConfig({heating_entities:['climate.a'],hot_water_entity:'climate.a'}));
for(const id of ['water_heater.tank','switch.immersion','climate.hot_water']) assert.equal(normalizeConfig({hot_water_entity:id}).hot_water_entity,id);
const nest={entity_id:'climate.nest',state:'heat_cool',attributes:{supported_features:3,target_temp_low:18,target_temp_high:22,hvac_modes:['heat','cool','heat_cool','off']}};
assert.equal(heatingCapabilities(nest).range,true);assert.equal(heatingCapabilities(nest).scalar,false);assert.equal(heatingCapabilities(nest).wiser,false);
assert.equal(heatingCapabilities({...nest,state:'heat',attributes:{supported_features:1,temperature:21}}).scalar,true);
assert.equal(heatingCapabilities({entity_id:'climate.basic',attributes:{supported_features:0}}).scalar,false);
assert.equal(heatingCapabilities({entity_id:'climate.room',attributes:{schedule_id:2,is_boosted:false}}).wiser,true);
assert.deepEqual(modeCommand({entity_id:'water_heater.tank'},'eco'),{service:'set_operation_mode',data:{operation_mode:'eco'}});
assert.deepEqual(modeCommand({entity_id:'switch.immersion'},'on'),{service:'turn_on',data:{}});
const genericCalls=[];
await entityAction({callService:async(...args)=>genericCalls.push(args),callWS:async()=>[{entity_id:'water_heater.tank',state:'eco',attributes:{operation_mode:'eco'}}]},'water_heater.tank','set_operation_mode',{operation_mode:'eco'},s=>s.attributes.operation_mode==='eco');
assert.equal(genericCalls[0][0],'water_heater');assert.equal(genericCalls[0][2].entity_id,'water_heater.tank');
console.log('Generic heating checks passed: multiple zones, climate capabilities, ranges, water heater modes, switch controls and service routing.');
